In [11]:
def test():
    print(' Test() for function')
    return
test()


 Test() for function


In [15]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj= Demo()   ## object creation
obj.test()    ## call for method

test() for the class and method


In [23]:
class Demo1:
    def fact(self,n):
        ## rerurn the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
        
       
p1=Demo1()
print(p1.fact(5))

120


In [ ]:
class Demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self):
        print(" p1= ",p1)
        print(" p2= ",p2)
c1=Demo2()
print(p1.accept(1))  ## it is not accepting because of Encapsuation
print(p2.accept(2)) ## the solution is below it

In [31]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))
    

300


In [48]:
## Sites Inheritance
class person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
## Derived CLass 
class Employee(person):
    def isEmployee(self):
        return True
emp = person("Anil")
emp2=Employee("Mahesh")
emp1 = person("Vamsi ")
print(emp.getName(),emp.isEmployee())
print(emp1.getName(),emp1.isEmployee())
emp = person("Akhil")
print(emp.getName(),emp.isEmployee())
print(emp2.getName(),emp2.isEmployee())

Anil False
Vamsi  False
Akhil False
Mahesh True


In [43]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(lst)

[1, 2, 3, 4]


In [52]:
lst= [1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [61]:

a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [69]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [74]:
np.zeros((2,2),dtype=np.int64)   ##array([0,0],[0,0]) 

array([[0, 0],
       [0, 0]], dtype=int64)

In [73]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [76]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [86]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

B=np.matrix(np.ones((4,3),dtype=np.int64))
np.asarray(B)[3]=5
print(B)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [5 5 5]]


In [92]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3] =14
np.asarray(A)[3][3]=16
np.asarray(A)[1][1]=3
np.asarray(A)[2][2]=2
print(A)

[[ 1  1  1  1]
 [ 1  3  1 14]
 [ 1  1  2  1]
 [ 1  1  1 16]]


In [3]:
## arrange() --Particular
## numpy.arrange(start,end,step)
## start -- value
## end- value
## Gap between one value to another value
import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [6]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [24]:
## Initiali and slicing of numpy
a1=np.array([(1,2,3),(4,5,6)])
print("Second row :",a1[1])
print("First row :",a1[0])
print("First coloumn",a1[:,0])
print("second coloumn",a1[:,1])
print("third coloumn",a1[:,2])

Second row : [4 5 6]
First row : [1 2 3]
First coloumn [1 4]
second coloumn [2 5]
third coloumn [3 6]


In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing coloumn :",a1[:,0])


Slicing Row : [1 4]


In [34]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing row :",a1[0])

Slicing row : [1 2 3]


In [27]:
a1=np.random.normal(5,1,10)
print(a1)

[5.63203631 1.93603458 5.7914672  2.89354065 4.0872111  4.99963241
 4.40659268 5.14622288 6.13743557 4.83126654]


In [28]:
## MIN -- Returns to the least number
## MAX -- Returns to the large number
## MEAN -- Mean
## Median --Median

In [32]:
a1=np.random.normal(5,1,10)
print(a1)
print(" Minimum value" ,np.min(a1))
print(" Maximum value", np.max(a1))
print(" Mean value", np.mean(a1))
print(" Median value", np.median(a1))

[5.09428294 6.72548675 5.47343305 4.53331613 5.53336851 4.79202008
 6.30654746 4.99779191 5.57119043 3.99845934]
 Minimum value 3.998459343677874
 Maximum value 6.725486749144891
 Mean value 5.302589660349001
 Median value 5.283857994067919


In [35]:
## Multiply of 1D Array
## numpy.dot(x,y)
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [37]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [ ]:
## Python is one of the most popular programming language for data analysis 
##  python is offering the lib called Pandas used for
##  importing analysing and makes more faster
##   Pandas Data frames
##  Data Analysis with python
##  

In [51]:
import pandas as pd
dict ={"Name":["Akhil","Anil","DInesh","Harsha","Ajay","Kranth"],
       "EmailID=":["akhil@gmail.com","Anil@gmail.com","dinesh@gmail.com","harsha@gmail.com","Ajay@gmail.com","Kranth@gmail.com"],
       "MobileNumber":[999,888,777,666,555,444],
       "Address":["Hyd","Hyd","Hyd","hyd","Hyd","Hyd"] }
b=pd.DataFrame(dict)
b.index=["01","02","03","04","05","06"]
print(b)


      Name          EmailID=  MobileNumber Address
01   Akhil   akhil@gmail.com           999     Hyd
02    Anil    Anil@gmail.com           888     Hyd
03  DInesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           666     hyd
05    Ajay    Ajay@gmail.com           555     Hyd
06  Kranth  Kranth@gmail.com           444     Hyd


In [56]:
## Super market
##import pandas as pd
##products = pd.read_csv('FileName.csv')
##print(products)